## Teleport configuration file. The "REMOTE_MACHINE" argument MUST be filled out manually
## prior to any usage.

## The following string is what ssh would use to connect to the remote machine.
## Usually it should follow the default format:
# REMOTE_MACHINE=USERNAME@REMOTE_URL
## However in case a custom ssh connection string has been specified in the .ssh/config
## file that string should be used:
# REMOTE_MACHINE=CUSTOM_SSH_CONNECTION_STRING
REMOTE_MACHINE=

## Unless there are specific needs for it, only the TELEPORT_LOCAL_DIRECTORY directory value should
## be edited.
LOCAL_TELEPORTER_PATH=~/
REMOTE_TELEPORTER_PATH=~/

